title: "Sigma"
description: "The Sigma Model Manipulation DSLs"
githubProject: "https://github.com/fikovnik/Sigma"

pygments: true

docs:
  - 
    title: Model Navigation and Modification
    url: model-navigation-and-modification.html
    desc: The common infrastructure facilitating model navigation and modification operations.
  - 
    title: Model Delegates
    url: model-delegates.html
    desc: Support for implementing derived features and operation bodies through Scala delegates.
  - 
    title: Model Consistency Checking
    url: model-consistency-checking.html
    desc: Model Consistency Checking DSL.
  - 
    title: M2M Transformation
    url: m2m-transformation.html
    desc: Model-to-Model Transformation DSL.
  - 
    title: M2T Transformation
    url: m2t-transformation.html
    desc: Model-to-Text Transformation DSL.
  - 
    title: Model Workflow Orchestration
    url: model-workflow-orchestration.html
    desc: Model Workflow Orchestration DSL.
