title: "SIGMA"
description: "SIGMA Model Manipulation"
githubProject: "https://github.com/fikovnik/Sigma"

pygments: true

markdown: kramdown

docs:
  - 
    title: Model Navigation and Modification
    url: model-navigation-and-modification.html
    desc: The common infrastructure facilitating model navigation and modification operations.
  - 
    title: Model Delegates
    url: model-delegates.html
    desc: Support for implementing derived features and operation bodies directly in Scala.
  - 
    title: Model Consistency Checking
    url: model-consistency-checking.html
    desc: A DSL for model consistency checking.
  - 
    title: M2M Transformation
    url: m2m-transformation.html
    desc: A DSL for model-to-model transformation.
  - 
    title: M2T Transformation
    url: m2t-transformation.html
    desc: A DSL for model-to-text transformation.
  - 
    title: Model Workflow Orchestration
    url: model-workflow-orchestration.html
    desc: A DSL for orchestrating model manipuation workflows.
